### ISSUE TITLE
snapshot not created  with no error message for Aurora Postgres (serverless)

### ISSUE THREAD

**Issue by jayvardhancs** [awslabs/pireporter#5]
Hello,

I'm trying to create snapshot for Aurora Server - postgres version 14 but snapshot was not created in the snapshot folder. I am using portable method to create the snapshot.  Do we have any way to run the command in debug mode, kindly advise. 

`
[ec2-user@ip-****************** portable]$ ./pireporter --create-snapshot --start-time 2024-07-01T10:00 --end-time 2024-07-01T11:00 -i pireporter2-instance-1 --include-logfiles

[ec2-user@ip-****************** portable]$ pwd
/home/ec2-user/pireporter/portable

[ec2-user@ip-****************** portable]$ ls
conf.json  genai  pireporter  pireporterPolicy.json  report.css  snapshots

[ec2-user@ip-****************** portable]$ cd snapshots/
[ec2-user@ip-****************** snapshots]$ ls

[ec2-user@ip-****************** snapshots]$

`

**Comment by aychin-aws** [comment]
Hi, serverless is not supported at the moment. Working on it.

**Comment by jayvardhancs** [comment]
Hi Aychin, Thanks for the update.
